import Link from 'next/link';
export const metadata = { title: 'Methods & reproducibility | Spatial Sensitivity Lab', description: 'Data provenance, processing, limitations and citation status for the urban cooling research demonstrator.' };
export default function Methods() { return <main className="methods-page" style={{maxWidth:960,margin:'auto',padding:'5vw 22px',lineHeight:1.6}}>
<Link href="/">← Spatial Sensitivity Lab</Link><h1>Methods & reproducibility</h1>
<p><b>Release status:</b> v0.3. IBSA and CBS social indicators are integrated where both measures are available; incomplete cells remain unscored.</p>
<h2>Data versions and boundaries</h2><ul>
<li>Amsterdam: PDOK administrative boundary; CBS neighbourhood layer labelled 2025 in the export script.</li><li>Brussels: UrbIS regional boundary and Brussels monitoring neighbourhoods; the exact neighbourhood vintage must be confirmed against the source GeoPackage.</li><li>ESA WorldCover 2021 (10 m); Copernicus imperviousness 2021 (10 m); GHSL GHS-POP 2020 (100 m).</li><li>Landsat 8/9 Collection 2 Level 2: summer observations, June–August 2019–2023.</li></ul><p>The source years differ. Scores compare cells within each city, not a common observation year or directly comparable city outcomes. Download rights and attribution requirements remain those of each source provider; the derived web files have no asserted blanket open licence.</p>
<h2>Processing and code</h2><ol><li>Project source rasters and boundaries to the common analytical CRS.</li><li>Intersect with 500 m grid, calculate land cover and population indicators, then normalise within each city.</li><li>Apply four disclosed weight combinations and their median; aggregate neighbourhood summaries by cell overlap area.</li><li>Validate association with Landsat surface temperature using Random Forest and five spatial folds.</li></ol><p>The <a href="https://github.com/polenbicer/spatial_sensitivity_lab/tree/main/scripts">public export and validation code</a> produces web files from a source GeoPackage that is not in the repository. The full upstream raster processing code, input snapshots, model seed and environment are not yet deposited. Consequently this is a documented partial reproduction path, not a fully reproducible computational archive. Repository tag and commit should be cited once the release is tagged.</p>
<h2>Limitations and planned sensitivity checks</h2><ul><li>Modifiable areal unit problem (MAUP): grid size and neighbourhood boundaries can change rankings.</li><li>Population is modelled (GHSL 2020), not an observed count per cell.</li><li>The indicators span 2019–2025 rather than a single year.</li><li>Social vulnerability is incomplete, especially Brussels in this model version.</li><li>No uncertainty intervals are provided for priority scores.</li><li>Next checks: Spearman and Kendall rank correlations and overlap of the highest priority quantile under alternative weights and spatial units.</li></ul>
<h2>About and citation</h2><p>Developed by Polen Biçer as an Urban Studies research demonstrator in the VUB–ULB academic context. Supervisor attribution and ethics approval status have not been supplied and are not asserted here. This site does not collect objections or contact details.</p><p><b>How to cite:</b> Biçer, P. (2026). <i>Spatial Sensitivity Lab</i>, research demonstrator, version 0.3, <a href="https://spatialsensitivitylab.vercel.app">spatialsensitivitylab.vercel.app</a>. DOI pending: no Zenodo deposit is claimed.</p>
<h2>Version log</h2><p>v0.3 (29 September 2026): IBSA/CBS social indicators, vulnerability-informed scenario and sensitivity metrics.</p>
</main> }
